export const dynamicControlAttrName = 'dynamic-control';
export const COMPONENT_FACTORY = 'COMPONENT_FACTORY';
export const COMPONENT_REF = 'COMPONENT_REF';
export const ABSTRACT_DYNAMIC_CONTROL = 'ABSTRACT_DYNAMIC_CONTROL';
export const DYNAMIC_CONTROLS_DICTIONARY = 'DYNAMIC_CONTROLS_DICTIONARY';
export const VALIDATORS_DICTIONARY = 'VALIDATORS_DICTIONARY';
