name: Base workflow for build.

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      appName:
        required: true
        type: string
      artifactName:
        type: string
        default: ''
  
jobs: 
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Restore variables
        uses: actions/cache/restore@v3
        with:
          path: 'temp/variables.json'
          key: shared-variables-${{ github.run_id }}-${{ github.run_attempt }}
      
      - name: Set env variables
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const sharedVariables = JSON.parse(fs.readFileSync('temp/variables.json', { encoding: 'utf8' }))
            Object.entries(sharedVariables).forEach(([name, value]) => {
              core.exportVariable(name, value);
            });

      - uses: actions/checkout@v2
        name: Checkout Base
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore node_modules
        uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: ${{ env.DEPENDENCIES_CACHE_KEY }}
          restore-keys: ${{ env.DEPENDENCIES_RESTORE_KEY }}
      
      - name: Lint
        run: npx nx lint ${{ inputs.appName }} --quiet

      - name: Test
        run: npx nx test ${{ inputs.appName }} --configuration=single-run

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Restore variables
        uses: actions/cache/restore@v3
        with:
          path: 'temp/variables.json'
          key: shared-variables-${{ github.run_id }}-${{ github.run_attempt }}
      
      - name: Set env variables
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const sharedVariables = JSON.parse(fs.readFileSync('temp/variables.json', { encoding: 'utf8' }))
            Object.entries(sharedVariables).forEach(([name, value]) => {
              core.exportVariable(name, value);
            });

      - uses: actions/checkout@v2
        name: Checkout Base
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore node_modules
        uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: ${{ env.DEPENDENCIES_CACHE_KEY }}
          restore-keys: ${{ env.DEPENDENCIES_RESTORE_KEY }}
      
      - name: Build
        run: npx nx build ${{ inputs.appName }}
      
      - name: Upload app artifacts
        if: ${{ inputs.artifactName }}
        uses: actions/upload-artifact@master
        with:
          name: ${{ inputs.artifactName }}
          path: dist